unprocessed_folder: "C:/Lavori/VGI-IL-PACHERA/"
converted_folder: "C:/Lavori/VGI-IL-PACHERA/"
to_revert_folder: "C:/Lavori/VGI-IL-PACHERA/"
reverted_folder: "C:/Lavori/VGI-IL-PACHERA/"
tmp_folder: "C:/Lavori/VGI-IL-PACHERA/"