
refresh_rate: 30 seconds

appenders:
  stdout:
    kind: console
    
  file_logger:
    kind: rolling_file
    path: logs/app.log
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} | {({l}):5.5} | {f}:{L} — {m}{n}"
    policy:
      trigger:
        kind: size
        limit: 10 mb
      roller:
        kind: fixed_window
        pattern: logs/step/step_{}.zip
        count: 14
        base: 1

root:
  level: debug
  appenders:
    - stdout
    - file_logger

#loggers:
#  step:
#    level: debug
#    appenders:
#      - step_ap


  